services:
  stayease-app:
    image: stayease-app:latest
    container_name: stayease_app
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    volumes:
      - ./src/main/resources/certs/private-key.pem:/app/certs/private-key.pem
      - ./src/main/resources/certs/public-key.pem:/app/certs/public-key.pem

  db:
    image: postgres:alpine
    restart: always
    container_name: stayease_db
    environment:
      POSTGRES_URL: ${DB_URL}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: stayease_redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
