spring:
  application:
    name: stayease
  config:
    import: optional:.env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      ssl:
        enabled: true
      timeout: 60000
    jdbc:
      repositories:
        enabled: false
  mail:
    host: smtp.mailersend.net
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

midtrans:
  server:
    key: ${MIDTRANS_SERVER_KEY}
  client:
    key: ${MIDTRANS_CLIENT_KEY}
  is:
    production: false

cloudinary:
  cloud:
    name: ${CLOUDINARY_NAME}
  public:
    key: ${CLOUDINARY_KEY}
  secret:
    key: ${CLOUDINARY_SECRET_KEY}